cabal-version:      2.4
name:                kiln
version:             0.2.1
synopsis:            Kiln builder
license:             MIT
license-file:        LICENSE
build-type:          Simple
data-files:
    template/default/**/*.css
    template/default/**/*.html
    template/default/**/*.js
    template/default/**/*.json
    template/default/**/*.md
    template/default/**/*.otf
    template/default/**/*.png
    template/default/**/*.svg
    template/default/**/*.ttf
    template/default/**/*.txt
    template/default/**/*.woff
    template/default/**/*.woff2
    template/default/res/latex-css-1.13.0/LICENSE
    template/default/res/mathjax-4.0.0/LICENSE
    template/flow/**/*.css
    template/flow/**/*.html
    template/flow/**/*.js
    template/flow/**/*.jpg
    template/flow/**/*.json
    template/flow/**/*.md
    template/flow/**/*.png

library
    hs-source-dirs:   src
    exposed-modules:  Kiln.Init
                    , Kiln.Config
                    , Kiln.Clean
                    , Kiln.Build
                    , Kiln.FileTree
                    , Kiln.Str
                    , Kiln.Build.Page
                    , Kiln.Build.Post
                    , Kiln.Build.PostEntry
                    , Kiln.Build.SearchDb
                    , Kiln.Build.FontSubset
                    , Kiln.Build.Cache
    other-modules:    Paths_kiln
    autogen-modules:  Paths_kiln
    build-depends:    base >=4 && <5, directory, filepath, aeson, process, containers, time
    default-language: GHC2024

executable kiln
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    base >=4 && <5, kiln
    default-language: GHC2024
    ghc-options:      -O2

test-suite kiln-test
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    hs-source-dirs:     test
    other-modules:      Kiln.ConfigSpec
                      , Kiln.CleanSpec
                      , Kiln.InitSpec
                      , Kiln.StrSpec
                      , Kiln.Build.PageSpec
                      , Kiln.BuildSpec
                      , Kiln.TestUtil
                      , Paths_kiln
    autogen-modules:    Paths_kiln
    build-depends:      base >=4 && <5, kiln, hspec, aeson, bytestring, directory, filepath, containers
    build-tool-depends: hspec-discover:hspec-discover
    default-language:  GHC2024
