cabal-version:      2.4
name:                kiln
version:             0.1.1
synopsis:            Kiln builder
license:             MIT
license-file:        LICENSE
build-type:          Simple
data-files:
    template/hello-kiln/**/*.css
    template/hello-kiln/**/*.html
    template/hello-kiln/**/*.js
    template/hello-kiln/**/*.json
    template/hello-kiln/**/*.md
    template/hello-kiln/**/*.otf
    template/hello-kiln/**/*.png
    template/hello-kiln/**/*.svg
    template/hello-kiln/**/*.ttf
    template/hello-kiln/**/*.txt
    template/hello-kiln/**/*.woff
    template/hello-kiln/**/*.woff2
    template/hello-kiln/res/latex-css-1.13.0/LICENSE
    template/hello-kiln/res/mathjax-4.0.0/LICENSE

library
    hs-source-dirs:   src
    exposed-modules:  Kiln.Init
                    , Kiln.Config
                    , Kiln.Clean
                    , Kiln.Build
                    , Kiln.FileTree
                    , Kiln.Template
                    , Kiln.Index
    other-modules:    Paths_kiln
    autogen-modules:  Paths_kiln
    build-depends:    base >=4 && <5, directory, filepath, aeson, process
    default-language: GHC2024

executable kiln
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    base >=4 && <5, kiln
    default-language: GHC2024
    ghc-options:      -O2

test-suite kiln-test
    type:               exitcode-stdio-1.0
    main-is:            Spec.hs
    hs-source-dirs:     test
    other-modules:      Kiln.ConfigSpec
                      , Kiln.CleanSpec
                      , Kiln.InitSpec
                      , Kiln.TemplateSpec
                      , Kiln.IndexSpec
                      , Kiln.BuildSpec
                      , Kiln.TestUtil
    build-depends:      base >=4 && <5, kiln, hspec, aeson, bytestring, directory, filepath
    build-tool-depends: hspec-discover:hspec-discover
    default-language:  GHC2024
