module Test.UT.Modules.FontSubset (suiteName, testCases) where

import Modules.Config
import Modules.FontSubset
import System.Directory
  ( createDirectoryIfMissing
  , doesFileExist
  )
import System.FilePath ((</>))
import Test.Framework.Asserts
import Test.Framework.Fixtures
  ( setupFontSubsetFixtureTree
  , writeFakePyftsubsetWithTrace
  )
import Test.Framework.Paths
import Test.Framework.TestSuite

suiteName :: String
suiteName = "FontSubset"

testCases :: [TestCase]
testCases =
  [ testMkFontSetDeduplicatesChars
  , testMkPyftsubsetArgsStable
  , testGenFontSubsetWritesFontSetAndCallsPyftsubset
  ]

testMkFontSetDeduplicatesChars :: TestCase
testMkFontSetDeduplicatesChars =
  mkTestCase "mkFontSet deduplicates characters from one input string" $ do
    let fontSet = mkFontSet "aabbccddaa"
    assertTrue "font set should contain unique char a" ('a' `elem` fontSet)
    assertTrue "font set should contain unique char b" ('b' `elem` fontSet)
    assertTrue "font set should contain unique char c" ('c' `elem` fontSet)
    assertTrue "font set should contain unique char d" ('d' `elem` fontSet)
    assertEq "font set should contain exactly 4 unique chars" 4 (length fontSet)

testMkPyftsubsetArgsStable :: TestCase
testMkPyftsubsetArgsStable =
  mkTestCase "mkPyftsubsetArgs returns deterministic production args" $ do
    assertEq "pyftsubset args should match configured production constants"
      [ originFontFilePath
      , "--text-file=" ++ fontSetPath
      , "--flavor=woff2"
      , "--output-file=" ++ subsetFontFilePath
      ]
      mkPyftsubsetArgs

testGenFontSubsetWritesFontSetAndCallsPyftsubset :: TestCase
testGenFontSubsetWritesFontSetAndCallsPyftsubset =
  mkTestCase "genFontSubset merges charset artifacts, writes fontset.txt and invokes pyftsubset" $ do
    withCasePathsInSandbox suiteName "genFontSubsetWritesFontSetAndCallsPyftsubset" [] $ \casePaths -> do
      let workRoot = caseRootDir casePaths
          binDir = workRoot </> "bin"
          tracePath = workRoot </> "pyftsubset.trace"
      createDirectoryIfMissing True binDir
      writeFakePyftsubsetWithTrace (binDir </> "pyftsubset")
      setupFontSubsetFixtureTree
      withEnv "PYFTSUBSET_TRACE" tracePath $
        withPrependedPath binDir genFontSubset
      fontSetExists <- doesFileExist fontSetPath
      subsetExists <- doesFileExist subsetFontFilePath
      traceExists <- doesFileExist tracePath
      assertTrue "fontset.txt should be generated" fontSetExists
      assertTrue "subset font output should be generated by fake pyftsubset" subsetExists
      assertTrue "fake pyftsubset should leave invocation trace" traceExists
      fontSet <- readFile fontSetPath
      assertContains "fontset should include charset from first artifact" "A" fontSet
      assertContains "fontset should include charset from second artifact" "B" fontSet
      assertContains "fontset should include charset from index artifact" "Z" fontSet
      trace <- readFile tracePath
      assertContains "trace should contain flavor option" "--flavor=woff2" trace
      assertContains "trace should contain output-file option"
        ("--output-file=" ++ subsetFontFilePath)
        trace
